from typing import Dict, Any, List, Optional
from uuid import UUID
from sqlalchemy.ext.asyncio import AsyncSession
from app.ai.context_builder import ContextBuilder
from app.ai.tool_manager import ToolManager
from app.ai.providers import get_ai_provider

class AIOrchestrator:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.context_builder = ContextBuilder(db)
        self.tool_manager = ToolManager(db)
        self.ai_provider = get_ai_provider()

    async def gather_user_context(self, user_id: UUID) -> Dict[str, Any]:
        return await self.context_builder.build_user_context(user_id)

    async def process_user_message(
        self,
        user_id: UUID,
        message: str,
        history: Optional[List[Dict[str, str]]] = None
    ) -> Dict[str, Any]:
        context = await self.context_builder.build_user_context(user_id)

        # Build prompt with rich, verified context
        user_info = context.get("user", {})
        tasks_summary = context.get("tasks_summary", {})
        recent_tasks = context.get("recent_tasks", [])
        active_goals = context.get("active_goals", [])
        skills = context.get("skills", [])
        gaps = context.get("skill_gaps", [])
        today_focus = context.get("today_focus_mins", 0)

        skills_str = ", ".join([f"{s['name']} ({s['level']}/100)" for s in skills[:4]]) if skills else "No skills logged yet"
        goals_str = ", ".join([g["title"] for g in active_goals]) if active_goals else "None yet"
        gaps_str = ", ".join([f"{g['skill_name']} (-{g['gap']} pts, {g['severity']})" for g in gaps[:3]]) if gaps else "None detected"

        system_prompt = (
            f"You are the Think2Act AI Career & Productivity Coach for {user_info.get('name', 'the user')}.\n"
            f"Target Career Role: {user_info.get('target_role')}.\n"
            f"Work Hours: {user_info.get('work_start_time')} - {user_info.get('work_end_time')} (Preferred sprint: {user_info.get('preferred_sprint_minutes')}m).\n"
            f"Current Execution State:\n"
            f"- Pending Tasks: {tasks_summary.get('pending', 0)}, Completed: {tasks_summary.get('completed', 0)} ({tasks_summary.get('rate', 0)}% completion rate)\n"
            f"- Today's Logged Focus: {today_focus} minutes\n"
            f"- Active Goals: {goals_str}\n"
            f"- Key Skills: {skills_str}\n"
            f"- Skill Gaps: {gaps_str}\n\n"
            f"Guiding Principles:\n"
            f"1. Be direct, action-oriented, and evidence-driven.\n"
            f"2. Never hallucinate tasks or skills not present in the user context.\n"
            f"3. Propose high-leverage tasks or schedule blocks using available tools.\n"
            f"4. Any proposed task creation or scheduling will be shown to the user for explicit confirmation."
        )

        messages: List[Dict[str, str]] = []
        if history:
            messages.extend(history[-6:])
        messages.append({"role": "user", "content": message})

        tools = self.tool_manager.get_tool_definitions()

        # Generate response using configured provider
        provider_resp = await self.ai_provider.generate_response(
            system_prompt=system_prompt,
            messages=messages,
            tools=tools,
            context=context
        )

        proposed_actions: List[Dict[str, Any]] = []

        # Process each tool call generated by provider
        for tc in provider_resp.tool_calls:
            tool_res = await self.tool_manager.execute_tool(
                tool_name=tc.name,
                user_id=user_id,
                params=tc.arguments,
                confirmed=False  # Always require confirmation for mutation
            )
            if tool_res.success and tool_res.requires_confirmation:
                proposed_actions.append({
                    "action_type": tool_res.action_type,
                    "target_type": tool_res.target_type,
                    "target_id": tool_res.target_id,
                    "payload": tool_res.payload,
                    "requires_confirmation": True
                })

        return {
            "response_text": provider_resp.content,
            "proposed_actions": proposed_actions
        }
